definitions:
  store.Api:
    properties:
      apiGroupId:
        type: string
      describe:
        type: string
      id:
        type: string
      method:
        type: string
      name:
        type: string
      path:
        type: string
      plugins:
        type: string
      status:
        type: string
      targets:
        items:
          $ref: '#/definitions/store.Target'
        type: array
    type: object
  store.Target:
    properties:
      host:
        type: string
      method:
        type: string
      path:
        type: string
      port:
        type: string
      scheme:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /apis:
    get:
      parameters:
      - description: query, ?query=age:>:21,name:like:%jason%
        in: query
        name: query
        type: string
      - description: order, ?order=age:desc,created_at:asc
        in: query
        name: order
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: pageSize
        in: query
        name: pageSize
        type: integer
      responses:
        "200":
          description: api array
          schema:
            items:
              $ref: '#/definitions/store.Api'
            type: array
      summary: List
      tags:
      - Api
    post:
      parameters:
      - description: Api
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/store.Api'
          type: object
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create
      tags:
      - Api
  /apis/{apiId}:
    delete:
      parameters:
      - description: apiId
        in: path
        name: apiId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete
      tags:
      - Api
    get:
      parameters:
      - description: apiId
        in: path
        name: apiId
        required: true
        type: string
      responses:
        "200":
          description: api object
          schema:
            $ref: '#/definitions/store.Api'
            type: object
      summary: Get
      tags:
      - Api
    put:
      parameters:
      - description: api
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/store.Api'
          type: object
      - description: apiId
        in: path
        name: apiId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Put
      tags:
      - Api
  /plugins:
    get:
      summary: Get
      tags:
      - Plugin
swagger: "2.0"
