proxy:
  host: "0.0.0.0"
  port: 9991
  maxIdleConns: 1000
  maxIdleConnsPerHost: 1000
plugins:
  - name: "copy_request"
    path: "plugins/copy_request.so"
  - name: "request_size"
    path: "plugins/size.so"
  - name: "rate_limit"
    path: "plugins/rate.so"
  - name: "ip_black"
    path: "plugins/black.so"
  - name: "ip_white"
    path: "plugins/white.so"
  - name: "cors"
    path: "plugins/cors.so"
  - name: "jwt"
    path: "plugins/jwt.so"
  - name: "cache"
    path: "plugins/cache.so"

