etcd:
  endpoints:
    - "etcd:2379"
  dialTimeout: 5
  username: ""
  password: ""

proxy:
  host: "0.0.0.0"
  port: 9991
  maxIdleConns: 1000
  maxIdleConnsPerHost: 1000

httpServer:
  host: "0.0.0.0"
  port: 9992

plugins:
  - name: "copy_request"
    path: "/usr/local/src/ioa/plugins/copy_request.so"
  - name: "request_size"
    path: "/usr/local/src/ioa/plugins/size.so"
  - name: "rate_limit"
    path: "/usr/local/src/ioa/plugins/rate.so"
  - name: "ip_black"
    path: "/usr/local/src/ioa/plugins/black.so"
  - name: "ip_white"
    path: "/usr/local/src/ioa/plugins/white.so"
  - name: "cors"
    path: "/usr/local/src/ioa/plugins/cors.so"
  - name: "jwt"
    path: "/usr/local/src/ioa/plugins/jwt.so"
  - name: "cache"
    path: "/usr/local/src/ioa/plugins/cache.so"
  - name: "default_response"
    path: "/usr/local/src/ioa/plugins/default_response.so"
  - name: "token_to_userId"
    path: "/usr/local/src/ioa/plugins/token_to_userId.so"
