FROM golang:latest

ENV CONFIG_LOCATION /etc/ioa/
COPY ./config.yml ${CONFIG_LOCATION}
VOLUME ${CONFIG_LOCATION}

COPY . /usr/local/src/ioa/

RUN cd /usr/local/src/ioa && \
    make && \
    mv /release/* usr/local/bin

RUN echo "ioa-proxy --config $CONFIG_LOCATION" > /run.sh

ENTRYPOINT ["/bin/sh","/run.sh"]
