FROM golang:latest

ENV PROJECT_LOCATION /usr/local/src/ioa/
ENV CONFIG_LOCATION /etc/ioa/

COPY ./config.yml ${CONFIG_LOCATION}

VOLUME ${CONFIG_LOCATION}

COPY . ${PROJECT_LOCATION}

WORKDIR ${PROJECT_LOCATION}

RUN make; \
    mv release/* /usr/local/bin/

ENTRYPOINT ["ioa-httpServer", "--config", "/etc/ioa/"]
