definitions:
  model.Api:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      describe:
        type: string
      groupId:
        type: string
      id:
        type: string
      method:
        type: string
      name:
        type: string
      status:
        type: string
      updatedAt:
        type: string
    type: object
  model.ApiGroup:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      describe:
        type: string
      id:
        type: string
      is_default:
        type: boolean
      name:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /apiGroups:
    get:
      parameters:
      - description: query, ?query=age:>:21,name:like:%jason%
        in: query
        name: query
        type: string
      - description: order, ?order=age:desc,created_at:asc
        in: query
        name: order
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: pageSize
        in: query
        name: pageSize
        type: integer
      responses:
        "200":
          description: apiGroup array
          schema:
            items:
              $ref: '#/definitions/model.ApiGroup'
            type: array
      summary: List
      tags:
      - ApiGroup
    post:
      parameters:
      - description: ApiGroup
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.ApiGroup'
          type: object
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create
      tags:
      - ApiGroup
  /apiGroups/{apiGroupId}:
    delete:
      parameters:
      - description: apiGroupId
        in: path
        name: apiGroupId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete
      tags:
      - ApiGroup
    get:
      parameters:
      - description: apiGroupId
        in: path
        name: apiGroupId
        required: true
        type: string
      responses:
        "200":
          description: apiGroup object
          schema:
            $ref: '#/definitions/model.ApiGroup'
            type: object
      summary: Get
      tags:
      - ApiGroup
    patch:
      parameters:
      - description: apiGroup
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.ApiGroup'
          type: object
      - description: apiGroupId
        in: path
        name: apiGroupId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Patch
      tags:
      - ApiGroup
    put:
      parameters:
      - description: apiGroup
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.ApiGroup'
          type: object
      - description: apiGroupId
        in: path
        name: apiGroupId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Put
      tags:
      - ApiGroup
  /apis:
    get:
      parameters:
      - description: query, ?query=age:>:21,name:like:%jason%
        in: query
        name: query
        type: string
      - description: order, ?order=age:desc,created_at:asc
        in: query
        name: order
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: pageSize
        in: query
        name: pageSize
        type: integer
      responses:
        "200":
          description: api array
          schema:
            items:
              $ref: '#/definitions/model.Api'
            type: array
      summary: List
      tags:
      - Api
    post:
      parameters:
      - description: Api
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Api'
          type: object
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create
      tags:
      - Api
  /apis/{apiId}:
    delete:
      parameters:
      - description: apiId
        in: path
        name: apiId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete
      tags:
      - Api
    get:
      parameters:
      - description: apiId
        in: path
        name: apiId
        required: true
        type: string
      responses:
        "200":
          description: api object
          schema:
            $ref: '#/definitions/model.Api'
            type: object
      summary: Get
      tags:
      - Api
    patch:
      parameters:
      - description: api
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Api'
          type: object
      - description: apiId
        in: path
        name: apiId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Patch
      tags:
      - Api
    put:
      parameters:
      - description: api
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Api'
          type: object
      - description: apiId
        in: path
        name: apiId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Put
      tags:
      - Api
swagger: "2.0"
