http:
  host: "0.0.0.0"
  port: 9992
db:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: ""
  name: "ioa"
ioa:
  host: "0.0.0.0"
  port: 9991
plugins:
  - name: "request_size"
    path: "plugins/size.so"
  - name: "rate_limit"
    path: "plugins/rate.so"

