http:
  host: "0.0.0.0"
  port: 9992
ioa:
  host: "0.0.0.0"
  port: 9991
plugins:
  - name: "request_size"
    path: "plugins/size.so"
  - name: "rate_limit"
    path: "plugins/rate.so"
  - name: "ip_black"
    path: "plugins/black.so"
  - name: "ip_white"
    path: "plugins/white.so"

