// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-01-23 17:15:28.997388 +0800 CST m=+0.099977089

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/apis": {
            "get": {
                "tags": [
                    "Api"
                ],
                "summary": "List",
                "responses": {
                    "200": {
                        "description": "api array",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.Api"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Api"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "Api",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/store.Api"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/apis/{apiId}": {
            "get": {
                "tags": [
                    "Api"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "apiId",
                        "name": "apiId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "api object",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/store.Api"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Api"
                ],
                "summary": "Put",
                "parameters": [
                    {
                        "description": "api",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/store.Api"
                        }
                    },
                    {
                        "type": "string",
                        "description": "apiId",
                        "name": "apiId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Api"
                ],
                "summary": "Delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "apiId",
                        "name": "apiId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/apisWithTag": {
            "get": {
                "tags": [
                    "Api"
                ],
                "summary": "ListWithTag"
            }
        },
        "/plugins": {
            "get": {
                "tags": [
                    "Plugin"
                ],
                "summary": "Get"
            }
        },
        "/pluginsWithTag": {
            "get": {
                "tags": [
                    "Plugin"
                ],
                "summary": "Get"
            }
        }
    },
    "definitions": {
        "store.Api": {
            "type": "object",
            "properties": {
                "apiGroupId": {
                    "type": "string"
                },
                "describe": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "plugins": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "targets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.Target"
                    }
                }
            }
        },
        "store.Target": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "scheme": {
                    "type": "string"
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
