// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-12-26 17:37:07.289406 +0800 CST m=+0.156728352

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/apiGroups": {
            "get": {
                "tags": [
                    "ApiGroup"
                ],
                "summary": "List",
                "parameters": [
                    {
                        "type": "string",
                        "description": "query, ?query=age:\u003e:21,name:like:%jason%",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order, ?order=age:desc,created_at:asc",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "apiGroup array",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ApiGroup"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "ApiGroup"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "ApiGroup",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ApiGroup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/apiGroups/{apiGroupId}": {
            "get": {
                "tags": [
                    "ApiGroup"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "apiGroupId",
                        "name": "apiGroupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "apiGroup object",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ApiGroup"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "ApiGroup"
                ],
                "summary": "Put",
                "parameters": [
                    {
                        "description": "apiGroup",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ApiGroup"
                        }
                    },
                    {
                        "type": "string",
                        "description": "apiGroupId",
                        "name": "apiGroupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "ApiGroup"
                ],
                "summary": "Delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "apiGroupId",
                        "name": "apiGroupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "tags": [
                    "ApiGroup"
                ],
                "summary": "Patch",
                "parameters": [
                    {
                        "description": "apiGroup",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ApiGroup"
                        }
                    },
                    {
                        "type": "string",
                        "description": "apiGroupId",
                        "name": "apiGroupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/apis": {
            "get": {
                "tags": [
                    "Api"
                ],
                "summary": "List",
                "parameters": [
                    {
                        "type": "string",
                        "description": "query, ?query=age:\u003e:21,name:like:%jason%",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order, ?order=age:desc,created_at:asc",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "api array",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Api"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Api"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "Api",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Api"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/apis/{apiId}": {
            "get": {
                "tags": [
                    "Api"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "apiId",
                        "name": "apiId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "api object",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Api"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Api"
                ],
                "summary": "Put",
                "parameters": [
                    {
                        "description": "api",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Api"
                        }
                    },
                    {
                        "type": "string",
                        "description": "apiId",
                        "name": "apiId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Api"
                ],
                "summary": "Delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "apiId",
                        "name": "apiId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "tags": [
                    "Api"
                ],
                "summary": "Patch",
                "parameters": [
                    {
                        "description": "api",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Api"
                        }
                    },
                    {
                        "type": "string",
                        "description": "apiId",
                        "name": "apiId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/plugins": {
            "get": {
                "tags": [
                    "Plugin"
                ],
                "summary": "List",
                "parameters": [
                    {
                        "type": "string",
                        "description": "query, ?query=age:\u003e:21,name:like:%jason%",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order, ?order=age:desc,created_at:asc",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "plugin array",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Plugin"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Plugin"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "Plugin",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Plugin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/plugins/{pluginId}": {
            "get": {
                "tags": [
                    "Plugin"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pluginId",
                        "name": "pluginId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "plugin object",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Plugin"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Plugin"
                ],
                "summary": "Put",
                "parameters": [
                    {
                        "description": "plugin",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Plugin"
                        }
                    },
                    {
                        "type": "string",
                        "description": "pluginId",
                        "name": "pluginId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Plugin"
                ],
                "summary": "Delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pluginId",
                        "name": "pluginId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "tags": [
                    "Plugin"
                ],
                "summary": "Patch",
                "parameters": [
                    {
                        "description": "plugin",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Plugin"
                        }
                    },
                    {
                        "type": "string",
                        "description": "pluginId",
                        "name": "pluginId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/policys": {
            "get": {
                "tags": [
                    "Policy"
                ],
                "summary": "List",
                "parameters": [
                    {
                        "type": "string",
                        "description": "query, ?query=age:\u003e:21,name:like:%jason%",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order, ?order=age:desc,created_at:asc",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "policy array",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Policy"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Policy"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "Policy",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Policy"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/policys/{policyId}": {
            "get": {
                "tags": [
                    "Policy"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "policyId",
                        "name": "policyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "policy object",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Policy"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Policy"
                ],
                "summary": "Put",
                "parameters": [
                    {
                        "description": "policy",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Policy"
                        }
                    },
                    {
                        "type": "string",
                        "description": "policyId",
                        "name": "policyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Policy"
                ],
                "summary": "Delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "policyId",
                        "name": "policyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "tags": [
                    "Policy"
                ],
                "summary": "Patch",
                "parameters": [
                    {
                        "description": "policy",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Policy"
                        }
                    },
                    {
                        "type": "string",
                        "description": "policyId",
                        "name": "policyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Api": {
            "type": "object",
            "properties": {
                "apiGroupId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "describe": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "params": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Param"
                    }
                },
                "path": {
                    "type": "string"
                },
                "pluginConfig": {
                    "type": "string"
                },
                "plugins": {
                    "type": "string"
                },
                "policies": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "targets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Target"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.ApiGroup": {
            "type": "object",
            "properties": {
                "apis": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Api"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "describe": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isDefault": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "plugins": {
                    "type": "string"
                },
                "policies": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.Param": {
            "type": "object",
            "properties": {
                "apiId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "targetName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.Plugin": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "describe": {
                    "type": "string"
                },
                "file_path": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.Policy": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "plugins": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.Target": {
            "type": "object",
            "properties": {
                "apiId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "scheme": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
